version: 0.2

phases:
  install:
    commands:
      - echo "Installing Maven..."
      - mvn --version
  build:
    commands:
      - echo "Building the project..."
      - mvn clean package
artifacts:
  files:
    - target/*.jar
