version: 0.2

phases:
  install:
    commands:
      - echo "Installing Maven..."
      - mvn --version
  build:
    commands:
      - echo "Building the project..."
      - cd java
      - mvn clean package

artifacts:
  files:
    - java/target/*.jar

